---

yanic_user: yanic
yanic_group: www-data
yanic_port: 10001
yanic_webserver: "false"
yanic_nodes_enabled: true
yanic_nodes_version: 2
yanic_nodes_path: /var/www/html/meshviewer/data
yanic_state_path: /var/lib/yanic/state.json
yanic_repo_path: "github.com/FreifunkBremen/yanic"
yanic_tag: "v1.5.0"
yanic_influx2_enabled: false
yanic_influx2_hostname: "http://monitor.{{ dns_searchdomains}}:8086"
yanic_influx2_token: "Slt8N2QzZCuAINwi_U1EeOvafjryX46IsAIIiT4BMKNpGhYo8PsAsPZcyYvl1LJglfFmlqASKl0ervGJPgX1-A=="
yanic_influx2_organisation_id: "freifunk"
yanic_influx2_bucket: "freifunk"

yanic_influx_enabled: false
yanic_influx_hostname: "http://monitor.{{ dns_searchdomains}}:8086"
yanic_influx_database: "freifunk"
yanic_influx_username: "freifunk"
yanic_influx_password: "freifunk"
yanic_no_owner: true
yanic_central: false
yanic_central_server: false