---

- name: Install tunnel device configs
  template:
    src: 2x-tunnel.netdev.j2
    dest: /etc/systemd/network/25-{{ item.netdev }}.netdev
  loop: "{{ gretunnel_configures }}"

- name: Install tunnel network configs
  template:
    src: 2x-tunnel.network.j2
    dest: /etc/systemd/network/25-{{ item.netdev }}.link
  loop: "{{ gretunnel_configures }}"
